# Generated by Django 5.2.8 on 2025-12-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roommateprofile",
            name="hostel_room_no",
        ),
    ]
