# Generated by Django 5.2.8 on 2025-12-06 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_roommateprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommateprofile',
            name='cleanliness_level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='noise_tolerance',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '03001234567'", regex='^03\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='sleep_schedule',
            field=models.CharField(choices=[('Early', 'Early Bird'), ('Late', 'Night Owl')], max_length=10),
        ),
    ]
